# Generated by Django 6.0.4 on 2026-04-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner_webside',
            field=models.URLField(blank=True, null=True),
        ),
    ]
