"""
Django settings for drf1 project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta
from celery.schedules import crontab

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1mk&)5#my6m7exy73(l6_y9$fe^i^_0xw3_z437%wv+jnls&3&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'djoser',    
    'tasks',
    'products',
    'debug_toolbar',
    'drf_spectacular'
]

REST_FRAMEWORK = {
"DEFAULT_AUTHENTICATION_CLASSES": (
"rest_framework_simplejwt.authentication.JWTAuthentication",
),
}

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'products.middleware.CustomLogMiddleware',    
]

ROOT_URLCONF = 'drf1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drf1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
'default': {
'ENGINE': 'django.db.backends.postgresql',
'NAME': os.getenv("NAME", 'test'), 
'USER': os.getenv('USER_NAME', 'test'),
'PASSWORD': os.getenv('PASSWORD', 'test'),
'HOST': os.getenv('HOST', 'test'), 
'PORT': os.getenv('PORT', 'test')
}
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

SIMPLE_JWT = {
"ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
"REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

try: 
    from .local_settings import *
except ImportError:
    pass

INTERNAL_IPS = [
"127.0.0.1",
]

CACHES = {
"default": {
"BACKEND": "django.core.cache.backends.locmem.LocMemCache",
"LOCATION": "unique-snowflake",
}
}
# CACHES = {
# "default": {
# "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
# "LOCATION": os.path.join(BASE_DIR, "django_cache"),
# }
# }

CACHES = {
"default": {
"BACKEND": "django.core.cache.backends.redis.RedisCache",
"LOCATION": "redis://127.0.0.1:6379",
}
}

CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = "Europe/Warsaw"
USE_TZ = True
CELERY_TIMEZONE = "Europe/Warsaw"

CELERY_BEAT_SCHEDULE = {
    "send-summary-every-5-minutes": {
        "task": "tasks.tasks.send_periodic_summary",
        "schedule": 10.0,  
        "args": (["user1@example.com", "user2@example.com"],),
    },
    "cleanup-database-daily": {
        "task": "tasks.tasks.cleanup_old_logs",
        "schedule": 5.0,
    },
#     Zadanie 4 – Pierwsze zadanie z harmonogramem
# Użyj Celery Beat, aby uruchamiać zadanie log_timestamp() z poprzedniego ćwiczenia co
# 10 sekund.
    "log-timestamp-10-seconds": {
        "task": "tasks.tasks.log_timestamp",
        "schedule": 10.0,
    },    
#     Zadanie 6 – Harmonogram z crontab
# Skonfiguruj Celery Beat tak, aby zadanie count_users() uruchamiało się codziennie o
# godzinie 23:00.
    "count-users-every-day-at-23": {
        "task": "tasks.tasks.count_users",
        "schedule": crontab(hour=23, minute=0),
    },
    
    "count-users-every-day-at-23": {
        "task": "tasks.tasks.clear_logs",
        "schedule": crontab(hour=22, minute=0),
    },
    "get-website-title-timestamp-10-seconds": {
        "task": "tasks.tasks.get_website_title",
        "schedule": crontab(hour="*", minute=0)
    },
}