# Generated by Django 6.0.4 on 2026-04-19 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_bike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e66d1968-c3df-4716-a6f9-35fc1159431d'), primary_key=True, serialize=False),
        ),
    ]
