# Generated by Django 6.0.4 on 2026-04-19 20:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_bike_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f73cf2f0-5cfe-4c60-97e0-436ea3b3858a'), primary_key=True, serialize=False),
        ),
    ]
