# Generated by Django 6.0.3 on 2026-04-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ogloszenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('opis', models.TextField(max_length=10000)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ogloszenia',
            },
        ),
    ]
