# Generated by Django 6.0.3 on 2026-04-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogloszenia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ogloszenia',
            old_name='desciption',
            new_name='description',
        ),
    ]
