# Generated by Django 6.0.3 on 2026-04-02 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogloszenia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ogłoszenie',
            new_name='Ogloszenie',
        ),
    ]
