# Generated by Django 6.0.4 on 2026-04-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogloszenia', '0002_rename_ogloszenie_ogloszenia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ogloszenia',
            new_name='Ogloszenie',
        ),
    ]
