# Generated by Django 6.0.4 on 2026-04-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_author_email_author_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
