# Generated by Django 6.0.4 on 2026-04-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogloszenia', '0003_rename_ogloszenia_ogloszenie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
