# Generated by Django 6.0.4 on 2026-05-05 07:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_nazwisko', models.CharField(max_length=200)),
                ('zdjecie', models.ImageField(blank=True, help_text='Zdjęcie aktora', null=True, upload_to='aktorzy/')),
            ],
            options={
                'verbose_name': 'Aktor',
                'verbose_name_plural': 'Aktorzy',
            },
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Gatunek',
                'verbose_name_plural': 'Gatunki',
            },
        ),
        migrations.CreateModel(
            name='Rezyser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_nazwisko', models.CharField(max_length=200)),
                ('zdjecie', models.ImageField(blank=True, help_text='Zdjęcie reżysera', null=True, upload_to='rezyserzy/')),
            ],
            options={
                'verbose_name': 'Reżyser',
                'verbose_name_plural': 'Reżyserzy',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('data_premiery', models.DateField()),
                ('plakat', models.ImageField(blank=True, help_text='Plakat filmu', null=True, upload_to='plakaty/')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('aktorzy', models.ManyToManyField(related_name='filmy', to='kino.aktor')),
                ('gatunek', models.ManyToManyField(related_name='filmy', to='kino.gatunek')),
                ('rezyser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filmy', to='kino.rezyser')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Filmy',
                'ordering': ['-data_premiery'],
            },
        ),
        migrations.CreateModel(
            name='Seans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_rozpoczecia', models.DateTimeField()),
                ('cena', models.DecimalField(decimal_places=2, help_text='Cena biletu w złotówkach', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('liczba_miejsc', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)])),
                ('dostepne_miejsca', models.IntegerField(default=50)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seanse', to='kino.film')),
            ],
            options={
                'verbose_name': 'Seans',
                'verbose_name_plural': 'Seanse',
                'ordering': ['czas_rozpoczecia'],
            },
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc_miejsc', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Oczekująca'), ('confirmed', 'Potwierdzona'), ('cancelled', 'Anulowana'), ('completed', 'Zaakceptowana')], default='pending', max_length=20)),
                ('data_rezerwacji', models.DateTimeField(auto_now_add=True)),
                ('data_modificacji', models.DateTimeField(auto_now=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje', to=settings.AUTH_USER_MODEL)),
                ('seans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezerwacje', to='kino.seans')),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
                'ordering': ['-data_rezerwacji'],
            },
        ),
    ]
