"""Dodajnie kolumny data_utworzenia

Revision ID: 165b22ab1c11
Revises: 68c49f42a216
Create Date: 2026-03-19 20:30:46.712438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165b22ab1c11'
down_revision: Union[str, Sequence[str], None] = '68c49f42a216'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zadania', sa.Column('data_utworzenia', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zadania', 'data_utworzenia')
    # ### end Alembic commands ###
