"""Utworzenie tabeli tag i zadaniatag

Revision ID: 385941e3856b
Revises: 165b22ab1c11
Create Date: 2026-03-23 18:08:04.833863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '385941e3856b'
down_revision: Union[str, Sequence[str], None] = '165b22ab1c11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zadania_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zadanie_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['zadanie_id'], ['zadania.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zadania_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
