# Generated by Django 6.0.3 on 2026-04-14 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag_posttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='posttag',
            table='posts_tags',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
    ]
