"""Dodanie tabeli tags, dodanie tabeli powiązań zadania-tags

Revision ID: 94ca228c08c4
Revises: e2c57629a703
Create Date: 2026-03-22 20:32:45.230766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94ca228c08c4'
down_revision: Union[str, Sequence[str], None] = 'e2c57629a703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zadania_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zadanie_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['zadanie_id'], ['zadania.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zadania_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
