"""Dodanie kolumnt data_utworzenia

Revision ID: 9c418428357a
Revises: 90e46dc170ed
Create Date: 2026-03-24 19:19:03.096464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c418428357a'
down_revision: Union[str, Sequence[str], None] = '90e46dc170ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zadania', sa.Column('data_utworzenia', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zadania', 'data_utworzenia')
    # ### end Alembic commands ###
