"""Utworzenie tabeli tag i zadania tag

Revision ID: dc0b7427bf41
Revises: 94ca228c08c4
Create Date: 2026-03-23 18:07:52.676612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc0b7427bf41'
down_revision: Union[str, Sequence[str], None] = '94ca228c08c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
