"""Dodanie kolumny data_utworzenia

Revision ID: e2c57629a703
Revises: 7a43489d2c27
Create Date: 2026-03-22 14:54:54.730040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c57629a703'
down_revision: Union[str, Sequence[str], None] = '7a43489d2c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zadania', sa.Column('data_utworzenia', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zadania', 'data_utworzenia')
    # ### end Alembic commands ###
