"""Dodanie tabeli tags, dodanie tabeli powiazan zadania-tags

Revision ID: fd8f3d91c50e
Revises: 9c418428357a
Create Date: 2026-03-24 21:53:05.162284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd8f3d91c50e'
down_revision: Union[str, Sequence[str], None] = '9c418428357a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
