# Generated by Django 6.0.5 on 2026-06-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name_surname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='director',
            name='name_surname',
            field=models.CharField(max_length=200),
        ),
    ]
