# Generated by Django 6.0.4 on 2026-04-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogloszenia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ogloszenie',
            new_name='Ogloszenia',
        ),
    ]
