# Generated by Django 6.0.4 on 2026-04-09 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category_id',
            new_name='category',
        ),
    ]
