# Generated by Django 6.0.5 on 2026-05-24 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_screening', models.DateField(verbose_name='Data seansu')),
                ('start_time', models.TimeField(verbose_name='Rozpoczecie seansu')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Cena za bilet')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='movies.movie')),
            ],
            options={
                'ordering': ['start_time', 'date_screening'],
            },
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_places', models.PositiveIntegerField(verbose_name='Ilość miejsc')),
                ('status', models.CharField(choices=[('RESERVED', 'Zarezerwowana'), ('PAID', 'Opłacona'), ('CANCELLED', 'Anulowana')], default='RESERVED', max_length=20, verbose_name='Status')),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.screening')),
            ],
            options={
                'verbose_name': 'Rezerwacja',
                'verbose_name_plural': 'Rezerwacje',
            },
        ),
    ]
