# Generated by Django 6.0.5 on 2026-05-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_rezerwacja_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rezerwacja',
            name='status',
            field=models.CharField(choices=[('RESERVED', 'Zarezerwowana'), ('PAID', 'Opłacona'), ('CANCELLED', 'Anulowana')], default='RESERVED', max_length=20, verbose_name='Status'),
        ),
    ]
