# Generated by Django 6.0.5 on 2026-06-07 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('reservations', '0003_alter_rezerwacja_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='screening',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='movies.movie', verbose_name='Film'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_places', models.PositiveIntegerField(verbose_name='Ilość miejsc')),
                ('status', models.CharField(choices=[('RESERVED', 'Zarezerwowana'), ('PAID', 'Opłacona'), ('CANCELLED', 'Anulowana')], default='RESERVED', max_length=20, verbose_name='Status')),
                ('creat_at', models.DateTimeField(auto_now_add=True)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.screening', verbose_name='seans')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='uzytkownik')),
            ],
        ),
        migrations.DeleteModel(
            name='Rezerwacja',
        ),
    ]
