# Generated by Django 6.0.5 on 2026-06-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_screening_movie_reservation_delete_rezerwacja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screening',
            options={'ordering': ['date_screening', 'start_time']},
        ),
    ]
