"""dodanie tagów i relacji

Revision ID: 30378d4dc01f
Revises: b407365a2422
Create Date: 2026-04-13 13:16:22.168269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30378d4dc01f'
down_revision: Union[str, Sequence[str], None] = 'b407365a2422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tagi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zadanie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opis', sa.String(), nullable=False),
    sa.Column('zrobione', sa.Boolean(), nullable=False),
    sa.Column('data_utworzenia', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zadanie_tag',
    sa.Column('zadanie_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tagi.id'], ),
    sa.ForeignKeyConstraint(['zadanie_id'], ['zadanie.id'], ),
    sa.PrimaryKeyConstraint('zadanie_id', 'tag_id')
    )
    op.drop_table('zadania')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zadania',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('opis', sa.VARCHAR(), nullable=False),
    sa.Column('zrobione', sa.BOOLEAN(), nullable=False),
    sa.Column('data_utworzenia', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('zadanie_tag')
    op.drop_table('zadanie')
    op.drop_table('tagi')
    # ### end Alembic commands ###
