"""zadania / dodanie datetime

Revision ID: 5668db92c00a
Revises: 7f9f9d9413ce
Create Date: 2026-03-23 22:28:03.132127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5668db92c00a'
down_revision: Union[str, Sequence[str], None] = '7f9f9d9413ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zadania', sa.Column('data_utworzenia', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zadania', 'data_utworzenia')
    # ### end Alembic commands ###
