"""Utworzenie tabeli tag i zadania tag

Revision ID: 7f9f9d9413ce
Revises: e1569b52d84a
Create Date: 2026-03-23 18:07:54.088215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9f9d9413ce'
down_revision: Union[str, Sequence[str], None] = 'e1569b52d84a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zadania_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zadanie_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['zadanie_id'], ['zadania.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zadania_tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
