"""Utworzenie tabeli zadan

Revision ID: e1569b52d84a
Revises: 
Create Date: 2026-03-23 08:36:06.881000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1569b52d84a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zadania',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opis', sa.String(), nullable=False),
    sa.Column('zrobione', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zadania')
    # ### end Alembic commands ###
