"""Dodanie priorytet do Zadanie

Revision ID: eac6eabf416e
Revises: 139191e68bf6
Create Date: 2026-03-25 15:56:26.327564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eac6eabf416e'
down_revision: Union[str, Sequence[str], None] = '139191e68bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zadanie', sa.Column('priorytet', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zadanie', 'priorytet')
    # ### end Alembic commands ###
