"""dodanie tagu i tabeli posredniej

Revision ID: f98a172aaed0
Revises: fa14c7586f0a
Create Date: 2026-03-26 02:34:03.226212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98a172aaed0'
down_revision: Union[str, Sequence[str], None] = 'fa14c7586f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazwa')
    )
    op.create_table('zadanie_tag',
    sa.Column('zadanie_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['zadanie_id'], ['zadanie.id'], ),
    sa.PrimaryKeyConstraint('zadanie_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zadanie_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
