"""Dodanie data_utworzenia do Zadanie

Revision ID: fa14c7586f0a
Revises: eac6eabf416e
Create Date: 2026-03-25 16:01:23.742943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa14c7586f0a'
down_revision: Union[str, Sequence[str], None] = 'eac6eabf416e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zadanie', sa.Column('data_utworzenia', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zadanie', 'data_utworzenia')
    # ### end Alembic commands ###
