# Generated by Django 6.0.4 on 2026-05-12 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_mailnotification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mailNotification',
            new_name='EmailNotification',
        ),
        migrations.AlterModelTable(
            name='emailnotification',
            table='EmailNotification',
        ),
    ]
