# Generated by Django 6.0.4 on 2026-05-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_mailnotification_emailnotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_log', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('action_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
